version: '3'

services:

  nginx:
    build: .
    ports:
      - 80:80
    container_name: pycontw-nginx
    restart: always
    hostname: pycontw-nginx
    volumes:
      - ./log:/var/log/nginx


networks:
    default:
        external:
            name: pycontw-net
