version: '3'

services:

  nginx:
    build: .
    ports:
      - 80:80
      - 443:443
    container_name: pycontw-nginx
    restart: always
    hostname: pycontw-nginx
    volumes:
        - /var/www/letsencrypt:/var/www/letsencrypt
        - /var/lib/dehydrated:/var/lib/dehydrated

networks:
    default:
        external:
            name: pycontw-net
